### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by nasiriscript** [sm1ky/luIP-marzban#4]
Hi, I read docs and looks like this project is for sqlite database. any chance of supporting mysql in near future?

**Comment by sm1ky** [comment]
Hi!

This project works on any database. But you need a configured Marzban :) 

I myself have MySQL, I also checked SQLite3. The script runs on a websocket that is taken from Marzban and therefore it doesn’t care about the database

> 21 дек. 2023 г., в 23:58, Nasiri ***@***.***> написал(а):
> 
> Hi, I read docs and looks like this project is for sqlite database. any chance of supporting mysql in near future?
