### ISSUE TITLE
[Solved] API connection error

### ISSUE THREAD

**Issue by pero-shpak** [sm1ky/luIP-marzban#7]
In luIP-marzban:
TypeError: Cannot read properties of undefined (reading 'access_token')
    at Api.token (/opt/luIP-marzban/config.js:172:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebSocket.retryGetToken (/opt/luIP-marzban/config.js:50:21)
In Marzban:
"WebSocket /api/node/1/logs?interval=30&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbnRpY2Vuem9yIiwiYWNjZXNzIjoic3VkbyIsImlhdCI6MTcwNjk3NjA1MSwiZXhwIjoxNzA3MDYyNDUxfQ.Kb-KjC5aBS3oAnh5MssHqKp37jPtmQx5mdmTwUPY_ZI" 403

**Comment by sm1ky** [comment]
Hello, most likely you entered incorrect data from the Marzban panel. The script cannot pass authorization to obtain information about the logs. double check everythingAnd check if you can connect to Websocket yourself. I don't know why it returns 403Отправлено с iPhone3 февр. 2024 г., в 18:02, pero-shpak ***@***.***> написал(а):﻿
In luIP-marzban:
TypeError: Cannot read properties of undefined (reading 'access_token')
at Api.token (/opt/luIP-marzban/config.js:172:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async WebSocket.retryGetToken (/opt/luIP-marzban/config.js:50:21)
In Marzban:
"WebSocket /api/node/1/logs?interval=30&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbnRpY2Vuem9yIiwiYWNjZXNzIjoic3VkbyIsImlhdCI6MTcwNjk3NjA1MSwiZXhwIjoxNzA3MDYyNDUxfQ.Kb-KjC5aBS3oAnh5MssHqKp37jPtmQx5mdmTwUPY_ZI" 403

**Comment by pero-shpak** [comment]
I thought so too. But the login/password is definitely correct (copy/paste from variables). The problem may be that the version Marzban - Dev with MySQL DB?

**Comment by sm1ky** [comment]
No, i use dev version 🤷‍♂️

Write me on telegram @sm1ky 

Отправлено с iPhone

> 3 февр. 2024 г., в 18:22, pero-shpak ***@***.***> написал(а):
> 
> I thought so too. But the login/password is definitely correct (copy/paste from variables). The problem may be that the version Marzban - Dev?
>
